### ISSUE TITLE
Continued support?

### ISSUE THREAD

**Issue by TheDan64** [nlsnightmare/rails#1]
Hi, I came across this library as I'm working on a machine learning project. I think it's awesome that rail intends to be Keras-like in its API.

I was wondering if you plan to continue to improve this library? I could really use `LSTM` and `Dropout` layers for a `Sequential` model but have no idea how to implement them myself.

Thanks!

**Comment by nlsnightmare** [comment]
Hello! Sorry for the late reply. Currently I am too busy to work on the project. I do have long term plans to continue the project, but as of now, I wouldn't recommend relying on it.

**Comment by TheDan64** [comment]
Are you looking for any help? I'm interested in contributing and have started a fork here: https://github.com/TheDan64/rail
Would be happy to merge changes upstream if you have enough time to at least review PR(s)
